# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'GeoDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeoDemo
  pod 'WildGeo', :path => '../'

  target 'GeoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
